name: CCCMMO
main: ca.bc.southridge.ccc.mmo.MMO
version: 1.0
api-version: 1.14
commands:
  maxbuff:
    description: Maximally buffs you!
    usage: /maxbuff
  maxdebuff:
    description: Maximally debuffs you!
    usage: /maxdebuff